export const openingDays = [
  {
    value: "4",
    label: "อาทิตย์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
  {
    value: "5",
    label: "จันทร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
  {
    value: "6",
    label: "อังคาร",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
  {
    value: "7",
    label: "พุธ",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
  {
    value: "8",
    label: "พฤหัสบดี",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
  {
    value: "9",
    label: "ศุกร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
  {
    value: "10",
    label: "เสาร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
  },
];

export const openingDaysPlace = [
  {
    value: "4",
    label: "วันอาทิตย์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "5",
    label: "วันจันทร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "6",
    label: "วันอังคาร",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "7",
    label: "วันพุธ",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "8",
    label: "วันพฤหัสบดี",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "9",
    label: "วันศุกร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "10",
    label: "วันเสาร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
];

export const openingDaysShop = [
  {
    value: "4",
    label: "อาทิตย์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "5",
    label: "จันทร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "6",
    label: "อังคาร",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "7",
    label: "พุธ",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "8",
    label: "พฤหัสบดี",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "9",
    label: "ศุกร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
  {
    value: "10",
    label: "เสาร์",
    isChecked: false,
    isDisable: true,
    openTime: "08:00",
    closeTime: "20:00",
    is_open_24_hour: false,
  },
];
