export const typeOfFood = [
  {
    id: 1,
    name: "ชาบูสุกี้",
    img: "/images/shabu-suki.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=ชาบู สุกี้ยากี้ หม้อไฟ",
    alt: "พาทัวร์ ชาบูสุกี้",
  },
  {
    id: 2,
    name: "ปิ้งๆย่างๆ",
    img: "/images/grill.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=ปิ้งย่าง หมูกะทะ บาร์บีคิว",
    alt: "พาทัวร์ ปิ้งๆย่างๆ",
  },
  {
    id: 3,
    name: "อิ่มไม่อั้น",
    img: "/images/buffet.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=อาหารบุฟเฟ่ต์",
    alt: "พาทัวร์ อิ่มไม่อั้น",
  },
  {
    id: 4,
    name: "กินเส้น",
    img: "/images/noodle.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=ก๋วยเตี๋ยว ก๋วยจั๊บ โจ๊ก",
    alt: "พาทัวร์ กินเส้น",
  },
  {
    id: 5,
    name: "อะไรหวานๆ",
    img: "/images/sweets.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=คาเฟ่ ของหวาน ไอศกรีม เบเกอรี่ เครื่องดื่ม",
    alt: "พาทัวร์ อะไรหวานๆ",
  },
  {
    id: 7,
    name: "ทอดร้อนๆ",
    img: "/images/fried.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=อาหารฟาสต์ฟู้ด",
    alt: "พาทัวร์ ทอดร้อนๆ",
  },
  {
    id: 8,
    name: "แซ่บนัว",
    img: "/images/esan.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=อาหารอีสาน",
    alt: "พาทัวร์ แซ่บนัว",
  },
  {
    id: 9,
    name: "เกาหลี",
    img: "/images/korea.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=อาหารเกาหลี",
    alt: "พาทัวร์ เกาหลี",
  },
  {
    id: 10,
    name: "เจแปนนิด",
    img: "/images/japan.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=อาหารญี่ปุ่น",
    alt: "พาทัวร์ เจแปนนิด",
  },
  {
    id: 11,
    name: "มาทั้งทะเล",
    img: "/images/sea.png",
    url: "search?text=&search_type=all&score=all&location=nearby&open_date=&category=อาหารทะเล",
    alt: "พาทัวร์ มาทั้งทะเล",
  },
];
