import { IAuthen } from "interface/auth.interface";
import { IMaxcard, IPatoisMaxcard } from "interface/maxcard.interface";

export type TUser = {
  userAuthen: IAuthen;
  accessToken: string;
  userPhone: string;
  formType: string;
  userID: number | null;
  follower: number;
  following: number;
  patoisMaxcard: IPatoisMaxcard;
  maxCardData: IMaxcard;
  isLoadingMaxcard: boolean;
  name: string;
  countNumberOfNotification: number;
  isAutoBindMaxcard: string;
  isNewUser: string;
  coutNumberOfmerchantShop: number;
  coutNumberOfCart: number;
  isLoadingHeader: boolean;
  setFollowing: (data: number) => void;
  setFollower: (data: number) => void;
  setUserID: (data: number) => void;
  setUserPhone: (data: string) => void;
  setFormType: (data: string) => void;
  setUserAuthen: (data: IAuthen) => void;
  setAccessToken: (data: string) => void;
  setPatoisMaxcard: (data: IPatoisMaxcard) => void;
  setMaxcardData: (data: IMaxcard) => void;
  setIsLoadingMaxcard: (data: boolean) => void;
  setName: (data: string) => void;
  setCountNumberOfNotification: (data: number) => void;
  setCountNumberOfCart: (data: number) => void;
  setIsAutoBindMaxcard: (data: string) => void;
  setIsNewUser: (data: string) => void;
  setCountNumberOfMerchantShop: (data: number) => void;
  setIsLoadingHeader: (data: boolean) => void;
};
