export enum LOCAL_STORAGE_TYPE {
  AUTH_QUERY_STRING = "AUTH_QUERY_STRING",
  PAYMENT_BOOKING_ID = "PAYMENT_BOOKING_ID",
  PAYMENT_BOOKING_UNIQUE_ID = "PAYMENT_BOOKING_UNIQUE_ID",
}

export enum LOCAL_SEARCH_HISTORY {
  LOCAL_SEARCH_HISTORY = "LOCAL_SEARCH_HISTORY",
}

export enum COOKIE_STORE_NAME {
  USER_AUTHEN = "patois_user",
  USER_PHONE = "user-phone-patois",
}
